flexi_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from flexxi import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='home'),
    #path('special/',views.special,name='special'),
    path('logout/', views.user_logout, name='logout'),
    path('flexxi/', include('flexxi.urls'), name='flexxi'),
]

if	settings.DEBUG:				
    urlpatterns	+=	static(settings.MEDIA_URL,														
    document_root=settings.MEDIA_ROOT)

flexxi/urls.py
from django.urls import path
from flexxi import views

app_name = 'flexxi'

urlpatterns = [
    path('', views.index, name='home'),
    path('signup/', views.signup, name='signup'),
    path('user_login/',views.user_login,name='user_login'),
    path('blog/', views.blog, name='blog'),
    path('enquiries/', views.enquiries, name='enquiries'),
    path('computer/', views.computer, name='computer'),
    path('tag/<slug:tag_slug>/', views.blog, name='blog_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.detail, name='detail'),
]

flexxi/models.py
from django.db import models
from django.utils import timezone 
from django.contrib.auth.models	import User
from django.urls import	reverse
from taggit.managers import TaggableManager


class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

class PublishedManager(models.Manager):	    # Creating and defining custom manager
    def	get_queryset(self):	
        return	super(PublishedManager,	self).get_queryset().filter(status='published')

class Post(models.Model):
    STATUS_OPTIONS	= (('draft', 'Draft'),('published', 'Published'),)				
    title	=	models.CharField(max_length=350)				
    slug	=	models.SlugField(max_length=400, unique_for_date='publish')
    author	=	models.ForeignKey(User,	on_delete=models.CASCADE, related_name='blog_posts')
    photo   =   models.ImageField(upload_to='media/', null=True, blank=True)
    story	=	models.TextField()
    publish	=	models.DateTimeField(default=timezone.now)
    created	=	models.DateTimeField(auto_now_add=True)	
    updated	=	models.DateTimeField(auto_now=True)				
    status	=	models.CharField(max_length=10,	choices=STATUS_OPTIONS,	default='draft')

    class Meta:								
        ordering = ('-publish',)

    def	__str__(self):								
        return	self.title

    tags = TaggableManager()

    # Adding the custom	manager to the Post model
    objects	= models.Manager()  # Default manager.
    published =	PublishedManager()  # Created custom manager

    # Building canonical urls for Post objects
    def	get_absolute_url(self):
        return	reverse('flexxi:detail',
                        args=[self.publish.year, self.publish.month, self.publish.day, self.slug])
    
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

flexxi/forms.py
from django import forms
from .models import Comment, UserProfileInfo
from django.contrib.auth.models import User

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('first_name','last_name','email','username','password',)
        
class UserProfileInfoForm(forms.ModelForm):
     class Meta():
         model = UserProfileInfo
         fields = ('profile_pic',)

flexxi/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import CommentForm, UserForm, UserProfileInfoForm
from taggit.models import Tag
from django.db.models import Count
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    posts = Post.published.all()
    return render(request,'flexxi/index.html', {'posts':posts} )

def computer(request):
    return render(request,'flexxi/computer.html' )

def	blog(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 8) # 8 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)  # If page is not an integer deliver the first page
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)  # If page is out of range deliver last page of results
    return	render(request, 'flexxi/blog.html', { 'page':page, 'posts':posts, 'tag':tag })

def	detail(request, year, month, day, post):
    
    post = get_object_or_404(Post, slug=post, status='published', publish__year=year, publish__month=month, publish__day=day)
    
    comments = post.comments.filter(active=True)  # List of active comments for this post
    new_comment = None

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)  # A comment was posted
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)  # Create Comment object but don't save to database yet
            new_comment.post = post  # Assign the current post to the comment
            new_comment.save()  # Save the comment to the database
    else:
        comment_form = CommentForm()

    # List of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:4]

    return render(request, 'flexxi/detail.html', {'post':post, 'comments':comments, 'new_comment':new_comment, 'comment_form':comment_form, 'similar_posts':similar_posts })

def enquiries(request):
    return render(request, 'flexxi/enquiries.html')

def signup(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                print('got it')
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request,'flexxi/signup.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('home'))
            else:
                return HttpResponse("Inactive account!")
        else:
            print("Login attempt failed!")
            print("Username: {} and password: {} were used!".format(username,password))
            return HttpResponse("Invalid username and/or password!")
    else:
        return render(request, 'flexxi/login.html', {})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('home'))

flexxi/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
 <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="{% static 'flexxi/css/bootstrap.min.css' %}" rel="stylesheet">    
    <link href="{% static 'flexxi/css/flexxi.css' %}" type="text/css" rel="stylesheet" >
    <link href="https://fonts.googleapis.com/css?family=Merriweather|Sacramento&display=swap" rel="stylesheet">
    <title>{% block title %} AlexanderBlog {% endblock %}</title>
 </head>
 <body>
    <nav class="navbar nav-tabs navbar-expand-md bg-dark navbar-dark p-3 mb-5">
        <div class="container">
            <!-- Brand -->
            <a class="navbar-brand wrap" href="{% url 'flexxi:home' %}">AlexanderBlog</a>
            <!-- Toggler/collapsibe Button -->
            <button class="navbar-toggler" type="button" data-toggle="collapse"data-target="#collapsibleNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <!-- Navbar links -->
            <div class="collapse navbar-collapse justify-content-end" id="collapsibleNavbar">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link text-light wrap" href="{% url 'flexxi:home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-light wrap" href="{% url 'flexxi:blog' %}" >Blog</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link wrap" href="{% url 'admin:index' %}"><small>Admin</small><span class="sr-only">(current)</span></a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
    <div class="container-fluid footer bg-dark text-light mt-5">
        <div class="col-md-12 col-sm-12 p-5">
            <h1>Get in Touch</h1>
            <div class="mt-4">
                <a class="wrap" href="https://www.github.com/alexflexxy/" target="_blank">Github</a>
                <a class="wrap" href="https://www.twitter.com/alexanderflexxy/" target="_blank">Twitter</a>
                <a class="wrap" href="https://www.Facebook.com/Alex Okpere/" target="_blank">Facebook</a>&nbsp;
            </div>
            <p class="copyright mt-5">&copy copyright and designed by Alex Okpere 2021</p>
        </div>
    </div>
    
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'flexxi/js/jquery-3.3.1.slim.min.js' %}"></script>
    <script src="{% static 'flexxi/js/popper.min.js' %}"></script>
    <script src="{% static 'flexxi/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'flexxi/js/flexxi.js' %}"></script>
 </body>
</html>

flexxi/templates/flexxi/blog.html
{% extends "base.html" %}
{% load static %}

<title>{% block title %} Blog {% endblock %}</title>
{% block body_block %}
  <div class="">
    <div class="row jumbotron p-2 p-md-5 text-white rounded bg-dark">
      <div class="col-md-4 d-flex justify-content-end">
        <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
            <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
            <li data-target="#carouselExampleCaptions" data-slide-to="3"></li>
          </ol>
          <div class="carousel-inner">
            <div class="carousel-item active">
              <img src="{% static 'flexxi/images/lum.jpg' %}" class="d-block w-auto " alt="luminuous">
            </div>
            <div class="carousel-item">
              <img src="{% static 'flexxi/images/lumi.jpg' %}" class="d-block w-auto" alt="luminuous">
            </div>
            <div class="carousel-item">
              <img src="{% static 'flexxi/images/lum.jpg' %}" class="d-block w-auto" alt="luminuous">
            </div>
            <div class="carousel-item">
              <img src="{% static 'flexxi/images/lumi.jpg' %}" class="d-block w-auto" alt="luminuous">
            </div>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>
      <div class="col-md-8 ">
          <h3 class="display-5">Light Up Mechatronics </h3>
          <p class="">contact us for renewable energy systems such as solar wind and any electrical services including inverter power systems</p>
          <p>Address: C4 Olorunda Avenue, Patoko, Ogun State</p>
          <p>Email: dakesholaautoworld@gmail.com</p>
      </div>
    </div>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8 blog-main">
          <h3 class="pb-4 mb-4 border-bottom">
              The Tech Gist
          </h3>
          <div class="row blog_row m-3 text-left pb-3">
            {% if tag %}
              <h2>Posts tagged with "{{ tag.name }}"</h2>
            {% endif %}

              {% for post in posts %}
              <div class="col-md-12 col-sm-12 col-12 pb-5 pt-5 border-bottom">
                <div class="blog_container item_grid ">        
                    <div class="blog_content">
                      <div class="blog_image">
                          <a href="{{	post.get_absolute_url }}">
                            <img src=" {% if post.photo %} {{ post.photo.url }} 
                            {% else %} {% static 'flexxi/images/one.jpg' %} {% endif %} "  class="img-fluid float-left w-50 h-auto" >
                          </a>
                      </div>
                      <div class="w-50 float-right pl-5">
                          <h5>
                              <a href="{{	post.get_absolute_url }}"> {{ post.title }}</a>				
                          </h5>
                          <p> 
                            Author: {{ post.author }}, {{ post.publish }}
                          </p>
                          <p class="tags">
                            Tags:
                            {% for tag in post.tags.all %}
                              <a href="{% url 'flexxi:blog_by_tag' tag.slug %}">
                                  {{ tag.name }}
                              </a>
                              {% if not forloop.last %}, {% endif %}
                            {% endfor %}
                          </p>			
                          {{ post.story|truncatewords:10|linebreaks }}
                          <a href="{{	post.get_absolute_url }}"><small>continue reading >></small></a>
                      </div>
                    </div>
                </div>
              </div>
              {% endfor %}
              {% include "pagination.html" with page=posts %}
            </div>
          </div><!-- /.blog-main -->
        <aside class="col-md-4 blog-sidebar">
          <div class="p-4 mb-3 bg-light rounded">
            <a href="https://www.Facebook.com/Ben Benny/" target="_blank"><img src="{% static 'flexxi/images/phada-i.jpg' %}" alt="phada-i" class=""></a>
            <a href="https://www.Facebook.com/shoforteproductions/" target="_blank"><img src="{% static 'flexxi/images/forte.jpg' %}" alt="shoforte" class="mt-3"></a>
            <a href="https://www.instagram.com/Shoforteproductions/" target="_blank"><img src="{% static 'flexxi/images/forte-1.jpg' %}" alt="shofortepro" class="mt-3"></a>
            <button class="btn btn-success font-italic mt-3">Archives</button>
            <ol class="list-unstyled mb-0">
            <li><a href="#">January 2021</a></li>
            <li><a href="#">February 2021</a></li>
            <li><a href="#">March 2021</a></li>
            <li><a href="#">April 2021</a></li>
            <li><a href="#">May 2021</a></li>
            <li><a href="#">June 2021</a></li>
            <li><a href="#">July 2021</a></li>
            <li><a href="#">August 2021</a></li>
            <li><a href="#">September 2021</a></li>
            <li><a href="#">October 2021</a></li>
            </ol>
          </div>
        </aside><!-- /.blog-sidebar -->
      </div><!-- /.row -->
    </main><!-- /.container -->
  </div>
{% endblock %}

flexxi/templates/flexxi/detail.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %} {{ post.title }} {% endblock %}

{% block body_block %}
<div class="container">
    <main role="main" class="container">
    <div class="row">
        <div class="col-md-8 blog-main">
        <h3 class="pb-4 mb-4 border-bottom">
            The Tech Gist
        </h3>
        <div class="row blog_row m-3 text-left pb-3">
            <div class="col-md-12 col-sm-12 col-12 pb-5">
                <div class="blog_container item_grid">
                    <div class="blog_item">
                        <div class="blog_content">
                            <h2>{{	post.title	}}</h2>
                            <p>
                                Published {{ post.publish }} by {{ post.author }}
                            </p>
                            <div class="blog_image">
                                <img src=" {% if post.photo %} {{ post.photo.url }} 
                                {% else %} {% static 'flexxi/images/one.jpg' %} {% endif %} " class="img-responsive w-100 mb-3" >
                            </div>
                            <div class="detailed">
                                {{ post.story|linebreaks }} 
                            </div>

                            <h4>Similar posts</h4>
                            {% for post in similar_posts %}
                                <p>
                                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                                </p>
                            {% empty %}
                                There are no similar posts yet.
                            {% endfor %}

                            {% with comments.count as total_comments %}
                            <h4>
                                {{ total_comments }} comment{{ total_comments|pluralize }}
                            </h4>
                            {% endwith %}

                            {% for comment in comments %}
                            <div class="comment">
                                <p class="info">
                                    Comment {{ forloop.counter }} by {{ comment.name }}
                                    {{ comment.created }}
                                </p>
                                {{ comment.body|linebreaks }}
                            </div>
                            {% empty %}
                            <p>There are no comments yet.</p>
                            {% endfor %}

                            {% if new_comment %}
                            <h4>Your comment has been added.</h4>
                            {% else %}
                            <h4>Add a new comment</h4>
                            <form action="." method="post">
                                {{ comment_form|crispy }}
                                {% csrf_token %}
                                <p><input type="submit" value="Add comment"></p>
                            </form>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div><!-- /.blog-main -->

    <aside class="col-md-4 blog-sidebar">
        <div class="p-4 mb-3 bg-light rounded">
          <a href="https://www.Facebook.com/Ben Benny/" target="_blank"><img src="{% static 'flexxi/images/phada-i.jpg' %}" alt="phada-i" class=""></a>
          <a href="https://www.Facebook.com/Shoforteproductions/" target="_blank"><img src="{% static 'flexxi/images/forte.jpg' %}" alt="shoforte" class="mt-3"></a>
          <a href="https://www.instagram.com/Shoforteproductions/" target="_blank"><img src="{% static 'flexxi/images/forte-1.jpg' %}" alt="shofortepro" class="mt-3"></a>
          <button class="btn btn-success font-italic mt-3">Archives</button>
          <ol class="list-unstyled mb-0">
          <li><a href="#">January 2021</a></li>
          <li><a href="#">February 2021</a></li>
          <li><a href="#">March 2021</a></li>
          <li><a href="#">April 2021</a></li>
          <li><a href="#">May 2021</a></li>
          <li><a href="#">June 2021</a></li>
          <li><a href="#">July 2021</a></li>
          <li><a href="#">August 2021</a></li>
          <li><a href="#">September 2021</a></li>
          <li><a href="#">October 2021</a></li>
          </ol>
        </div>
      </aside><!-- /.blog-sidebar -->
</div><!-- /.row -->
</main><!-- /.container -->
</div>
{% endblock %}

flexxi/templates/flexxi/enquiries.html
{% extends 'base.html' %}
{% load static %} 

{% block body_block %}
<div class="">
	<p class="pb-3 detailed">Alex Okpere is a smart, prolific, full stack web developer with a 
		flair for creating elegant solutions in the least amount of time. His career objective is to 
		make positive and valued impact, serve with high sense of integrity and make the provision of 
		standard and quality services a way of life. A regular attendee of web developer meetups and 
		hackathons, computer science graduate and a tireless web designer/developer based in Lagos, 
		Nigeria. His passion for web development is second to none.
	</p>
</div>
<a class="btn btn-dark text-light mt-3" data-toggle="modal" data-target="#exampleModal" href="{% url 'flexxi:enquiries' %}">Enquiries</a>
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true"> 
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-tittle" id="exampleModalLabel">Contact Me</h4>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"></button>
				<span aria-hidden="true">&times;</span>
			</div>
			<div class="modal-body">
				<h5>Email: alex.okpere@gmail.com</h5>
				<h5>Phone: +2348027349310</h5>
			</div>
		</div>
	</div>
</div>

{% endblock %}

flexxi/templates/flexxi/index.html
{% extends "base.html" %}
{% load static %}

<title>{% block title %} Home {% endblock %}</title>
{% block body_block %}
<div class="">
    <div class="row mb-5">
        <div class="col-md-6 col-sm-12 col-12 text-left">
            <h1>Its all about Tech!</h1>
            <h4 class="py-3 pr-3 ">Meet Alex...</h4>
            <p class="pb-3 detailed">Alex Okpere is a smart, prolific, full stack web developer with a 
                flair for creating elegant solutions in the least amount of time. His career objective is to 
                make positive and valued impact, serve with high sense of integrity and make the provision of 
                standard and quality services a way of life. A regular attendee of web developer meetups and 
                hackathons, computer science graduate and a tireless web designer/developer based in Lagos, 
                Nigeria. His passion for web development is second to none.
            </p>
            <a class="text-light btn btn-dark" href="{% url 'flexxi:enquiries' %}">About Me</a>
            <button type="button" onclick="msg()"> Date and Time </button>
            <p id="demo" ></p>
        </div>
        <div class="col-md-6 col-sm-12 col-12 ">
            <img src="{% static 'flexxi/images/alexander.jpg' %} " alt="alex" class="img-fluid ">
        </div>
    </div>

    <h1 class="py-3">The Tech Gist</h1>
    <h4>Read about tech, innovations, web design, IT and many more!</h4>
    <div class="row my-3 text-left pb-3">
        {% for post in posts|slice:":3" %}
        <div class="col-md-4 col-sm-12 col-12 pb-5">            
            <div class="hover-effect">
                <img  src=" {% if post.photo %} {{ post.photo.url }} 
                {% else %} {% static 'flexxi/images/one.jpg' %} {% endif %}" class="w-100 img-fluid img-thumbnail" width="800" height="533" >
            </div>           
            <h4 class="pt-3">{{ post.title }}</h4>
            <p class="detailed">{{ post.story|truncatewords:20|linebreaks }} </p>
            <a class="wrap" href="{{post.get_absolute_url }}"><small>continue reading >></small></a>
        </div>
        {% endfor %}
    </div>
    <a href="{% url 'flexxi:blog' %}" class="wrap btn btn-dark text-light">Learn whats hot on tech news here</a>
    <div class="row bg-light mt-5">
        <div class="col-md-6 text-left">
            <div class='console-container '><span id='text'></span><div class='console-underscore' id='console'>&#95;</div></div>
         </div>
        <div class="col-md-6 col-sm-12 col-12 p-5">
            <h3 class="font-italic">Join Us at FlexxiDigital Solutions!</h3>
        </div>
    </div>
    <div class="row bg-info p-3 mb-5 text-light text-left">
        <div class="col-md-4 col-sm-12 col-12 pb-5">
            <div class="hover-effect">
                <img src="{% static 'flexxi/images/front.jpg' %} " alt="frontend" class="img-fluid" >
            </div>
            <h4 class="pt-3">Frontend website design</h4>
            <p class="detailed" >Learn HTML, HTML5, Bootstrap, CSS, CSS3, and JS. This training is a practical oriented
                training class.
            </p>
            <a class="text-light wrap" href="{% url 'flexxi:signup' %}"><small>Register</small></a>
        </div>
        <div class="col-md-4 col-sm-12 col-12 pb-5">
            <div class="hover-effect">
                <img src="{% static 'flexxi/images/combination.jpg' %} " alt="combination" class="img-fluid" >
            </div>
            <h4 class="pt-3">Web design & development</h4>
            <p class="detailed" >This is a combination of web design and web development training. 
                Learn how to create responsive HTML/CSS websites from scratch. It is a practical oriented training
            </p>
            <a class="text-light wrap" href="{% url 'flexxi:signup' %}"><small>Register</small></a>
        </div>
        <div class="col-md-4 col-sm-12 col-12 pb-5">
            <div class="hover-effect">
                <img src="{% static 'flexxi/images/back.jpg' %} " alt="backend" class="img-fluid" >
            </div>
            <h4 class="pt-3">Web app development</h4>
            <p class="detailed" > This is backend web development training. It is practical oriented.</p>
            <a class="text-light wrap" href="{% url 'flexxi:signup' %}"><small>Register</small></a>
        </div>
    </div>
    <div class="row my-3 text-left">
        <div class="col-md-6 col-sm-12 col-12 p-5">
            <h2>For Software Solutions?</h2>
            <h2>Please Call:</h2>
            <h2>+2348027349310</h2>
            <p>We would love to see how we can help you achieve your software solutions and IT goals!</p>
            <button type="button" class="btn btn-dark mt-3"><a class="text-light" href="mailto:alex.okpere@gmail.com">Contact Via Email</a></button>
            <div class="row py-5 pl-2">
                <div><a href="https://www.Facebook.com/Alex Okpere/" target="_blank"><img src="{% static 'flexxi/images/fb.png' %} " alt="fb" class="img-fluid m-2"></a></div>
                <div><a href="https://www.twitter.com/alexanderflexxy/" target="_blank"><img src="{% static 'flexxi/images/tw.png' %} " alt="tw" class="img-fluid m-2"></a></div>
                <div><a href="https:/www./instagram.com/saintflexxy/" target="_blank"><img src="{% static 'flexxi/images/instagram.jpg' %} " alt="instagram" class="img-fluid m-2"></a></div>
            </div>
        </div>
        <div class="col-md-6 col-sm-12 col-12 p-5 embed-responsive embed-responsive-16by9">
            <iframe src="https://www.google.com/maps/embed?pb=!1m16!1m12!1m3!1d31706.382043883772!2d3.246775524950624!3d6.60987602468276!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!2m1!1s9%20sam%20ayedun%20close%20ipaja!5e0!3m2!1sen!2sng!4v1637008591090!5m2!1sen!2sng" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
        </div>
        <a href="#">Back to top</a>
    </div>
</div>
{% endblock %}

flexxi/templates/flexxi/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %} 
User Login 
{% endblock %}

{% block body_block %}
  <div class="container jumbotron glass">
    <div class="row justify-content-center">
      <div class="col-md-6 col=12">
        <div class="register">
          <form method="post" action="{% url 'flexxi:user_login' %}">
            {% csrf_token %}
            {# Creating the login form with HTML#}
            <fieldset>
              <legend class="text-center">Login</legend>
                <label for="username">Username:</label>
                <input type="text" name="username" placeholder="Username"><br>
                <small id="usernameHelp" class="form-text text-muted">minimum of 8 characters</small><br>
                <label for="password">Password:</label>
                <input type="password" name="password" placeholder="Password"><br>
                <input class="myButton mt-3" width="170px" type="submit" name="" value="Login">
            </fieldset>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

flexxi/templates/flexxi/signup.html
{% extends "base.html" %}
{% load static %}
{% block title %} 
Sign Up
{% endblock %}

{% block body_block %}
{% load crispy_forms_tags %}
  <div class="container jumbotron glass">
    <div class="row justify-content-center">
      <div class="col-md-6 col-12">
        <div class="register"  >
          {% if registered %}
            <h2>Thank you for registering!</h2>
            <h3>Please <a class="nav-link" href="{% url 'flexxi:user_login' %}">login</a></h3>
          {% else %}
            <h1 class="text-center">Register Here</h1><br>
            <div class="" id="form">
              <form enctype="multipart/form-data" method="POST">
                {% csrf_token %}
                {{ user_form|crispy }}
                {{ profile_form|crispy }}
                <input class="myButton " type="submit" name="" value="Register">
              </form> 
            </div>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}